apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: campus-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6.0
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://:9092
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: campus-market
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka
