server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_market?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: change-me-super-secret-key-please-replace-with-longer-string-123456
  expiration-ms: 86400000

logging:
  level:
    com.campusmarket: INFO
