-- Schema bootstrap for PostgreSQL migration draft.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'STUDENT',
    nickname VARCHAR(64) NOT NULL,
    avatar_url VARCHAR(255),
    phone VARCHAR(32),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS goods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    description TEXT,
    category VARCHAR(64),
    price NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    cover_image_url VARCHAR(255),
    seller_id BIGINT NOT NULL REFERENCES users(id),
    published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_sold BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW'
);

CREATE INDEX IF NOT EXISTS idx_goods_status_category_published
    ON goods (status, category, published_at);

CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    goods_id BIGINT NOT NULL REFERENCES goods(id),
    quantity INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_cart_user_goods
    ON cart_items (user_id, goods_id);

CREATE TABLE IF NOT EXISTS chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES users(id),
    receiver_id BIGINT NOT NULL REFERENCES users(id),
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP,
    message_type VARCHAR(16) NOT NULL DEFAULT 'TEXT'
);

CREATE INDEX IF NOT EXISTS idx_chat_message_pair_created
    ON chat_message (sender_id, receiver_id, created_at);

CREATE TABLE IF NOT EXISTS flash_sale_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    description TEXT,
    original_price NUMERIC(10, 2) NOT NULL,
    flash_price NUMERIC(10, 2) NOT NULL,
    total_stock INTEGER NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flash_sale_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flash_sale_item_id BIGINT NOT NULL REFERENCES flash_sale_item(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(32) NOT NULL DEFAULT 'PREPARING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_flash_sale_user
    ON flash_sale_order (flash_sale_item_id, user_id);

CREATE INDEX IF NOT EXISTS idx_flash_sale_item_created
    ON flash_sale_order (flash_sale_item_id, created_at);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_id BIGINT NOT NULL REFERENCES goods(id),
    buyer_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_buyer_created
    ON orders (buyer_id, created_at);

CREATE INDEX IF NOT EXISTS idx_orders_goods_id
    ON orders (goods_id);

-- Placeholder for seed data inserts; migrate from MySQL dump as needed.
